- name: Configurar Raspberry Pi
  hosts: localhost
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes básicos
      apt:
        name:
          - htop
          - curl
          - git
          - unzip
        state: present
