- name: Atualizar sistema e instalar pacotes básicos
  hosts: localhost
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes básicos
      apt:
        name:
          - htop
          - curl
          - git
          - unzip
          - wget
          - gnupg
          - lsb-release
          - ca-certificates
          - apt-transport-https
        state: present
